### ISSUE TITLE
Playable Eggman and Tikal in Test Spawn (request)

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/sadx-mod-loader#101]
Although the Character Select mod exists, it would be nice to have the minimum required changes built into the Mod Loader to get these characters to load in Test Spawn.

**Comment by Sora-yx** [comment]
Done [4517283](https://github.com/X-Hax/sadx-mod-loader/commit/4517283b5596d7f028ad32428a011b350be94f96)

**Comment by Sora-yx** [comment]
Done in [4517283](https://github.com/X-Hax/sadx-mod-loader/commit/4517283b5596d7f028ad32428a011b350be94f96)
