### ISSUE TITLE
Test Spawn: Ice Cap spawn issues

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/sadx-mod-loader#102]
Testspawn to Ice Cap Acts 2 and 3 causes the following. Restarting the level corrects it.
There was [a fix](https://github.com/sonicretro/sadx-test-spawn/commit/dcce47f9a9b626142a9e69d722c5346c66ebbf0b#diff-f050d9945f6ad4c271945acd24bd66186f1a8217969f18ff073b0406367c44a1R181) for this in the old testspawn mod.

![image](https://user-images.githubusercontent.com/23312549/177009337-902eac2f-e0bb-41fe-9edf-809e158b810c.png)
![image](https://user-images.githubusercontent.com/23312549/177009339-95d4fbb7-6811-43a8-9bf9-7e07ccfdb779.png)

**Comment by Sora-yx** [comment]
Fixed in [ab01de0](https://github.com/X-Hax/sadx-mod-loader/commit/ab01de0017ae0afda7d1d5688413eb43810f53a1)
