### ISSUE TITLE
FMV and Material Bugs

### ISSUE THREAD

**Issue by ElectroNuke** [X-Hax/sadx-mod-loader#112]
I just updated the mod loader, and I'm surprised at the amount of built-in fixes being added! However, I think the update might've brought along some unintended graphical bugs. The first involves the Egg Viper. Eggman's low-poly model inside has white skin with the material color fixed enabled.

![1](https://user-images.githubusercontent.com/33000916/185765794-2711b183-c662-4d03-95c4-095dcdb96156.png)

The second is an issue that existed before, but it was able to be fixed before the update. When the FMVs fade out, a black square forms in the corner of the screen. This was able to be fixed by switching "FMV fill mode" to "Fit", but after the update, the black square still appears, even with this setting.

![2](https://user-images.githubusercontent.com/33000916/185765870-bcda6941-2453-4e1a-b894-5a78090b5b98.png)

**Comment by PiKeyAr** [comment]
> Eggman's low-poly model inside has white skin with the material color fixed enabled.


This is normal and consistent with other versions of the game. You can disable material color fixes if you don't want it.


>  When the FMVs fade out, a black square forms in the corner of the screen.

You likely have a mod order problem with DC Conversion and AI HD FMVs.

**Comment by ElectroNuke** [comment]
Wow. It really has been a while since I've played the GC version, huh? Guess his skin IS white. I don't have AI HD FMVs or DC Conversion installed, however. I like playing it like the GC version.

**Comment by PiKeyAr** [comment]
The FMV thing is an issue in the vanilla 2004 PC port. It's fixed in DC Conversion and possibly other mods, but the fix isn't in the mod loader at the moment. I think there's only one FMV (the Egg Carrier escape sequence) affected by it. It's always been there, and the settings in the Mod Loader have no effect on it.

**Comment by ElectroNuke** [comment]
Okay, well, I could always try disabling most of DC Conversion, although this happens to the water.

![3](https://user-images.githubusercontent.com/33000916/185813209-847b32eb-a090-4994-b82b-e560adc3df28.png)

**Comment by ElectroNuke** [comment]
Okay, I tried disabling everything in DC Conversion. That seems to have done it.
