### ISSUE TITLE
Game Health Check / Mod Troubleshooter

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/sadx-mod-loader#123]
Just wanted to share an idea I've been contemplating for a while: a game health check button in SADX Mod Manager.

This would work almost the same as a mod manifest check, but for the base game. We could have a manifest for files in the game's system folder to check if the installation has been modified: edited or missing PVMs, rebuilt CHRMODELS etc. 

For the sounddata folder, we might have to use two hashes and check a different location because it could be either in system or in the main folder. We might also reuse the check SA Tools Hub does for sonic.exe to account for EXEs that have different icons and manifests but the same game data.

This would be even better combined with #27 to let the player know if there are any potential issues with their game or system affecting mods. For VS runtimes, just checking if it's installed (2010, 2012, 2013) and checking if it's the latest version (2015-2022) and providing links would be good enough. It could also check whether DirectX 9.0c and Windows Media Player are installed.

**Comment by Sora-yx** [comment]
This has been done with the new Manager.
