### ISSUE TITLE
Stuttering in Sonic Adventure with curious properties...?

### ISSUE THREAD

**Issue by TailsGuy** [X-Hax/sadx-mod-loader#124]
I've never made an issue before on this repo, but I'll make it as informative as possible.

CPU - AMD Ryzen 7 5700X
GPU - NVIDIA GeForce RTX 3070
RAM - Crucial Ballistix 32GB 3200Mhz RAM (Overclocked to 3600Mhz)

Sonic Adventure's frame pacing isn't very good, and no workarounds exist, as far as I know.
I've noticed for a long time is that from you're perfectly fine for maybe three minutes after boot, but when you really get into the weeds after about five to ten minutes it degrades rapidly.

Here are my graphical settings on SADX, and I used SADX Mod Installer, not BetterSADX, as it's outdated somewhat.
I haven't edited any particular parameters in the NVIDIA graphics panel for this game specifically. I also don't own a G-SYNC monitor, just plain old Sceptre 60hz glory.

If it matters, I launch from Steam, since I can't use my PS5 controller if I launch in the Mod Loader, even though Steam Input **seems** to be working just fine.

![Screenshot 2023-07-25 050301](https://github.com/X-Hax/sadx-mod-loader/assets/70661792/00b9f40a-dfa8-4a92-90ed-d9b2ccd71cb1)
![Screenshot 2023-07-25 045056](https://github.com/X-Hax/sadx-mod-loader/assets/70661792/60b131ef-942f-48f2-b819-0d56b4b9a420)

What's **strange** is that I can't seem to record this phenomenon. I use OBS, and I can't really record the stutters, they do happen, but it doesn't translate to the footage whatsoever, it's all smooth.

Maybe I'll try again, but for now I'll put this issue up as is.
I actually uninstalled MSI Afterburner as it was causing stuttering in Sonic 3 A.I.R., but it has no effect on SADX.

https://github.com/X-Hax/sadx-mod-loader/assets/70661792/3600b163-263d-4014-b10a-acc2611eeb1d

Here's the video, if anyone cares to check it out. Unfortunately I had to compress it down so I can host it on GitHub.
It's *also* apparent that it's in thirty frames per second, sorry... Not very useful.

**Comment by PiKeyAr** [comment]
SF94 has released [a new experimental version](https://github.com/michael-fadely/sadx-frame-limit/releases/) of the Frame Limit mod that appears to fix the stuttering.

**Comment by TailsGuy** [comment]
Interesting, I'll go check it out.

**Comment by TailsGuy** [comment]
It runs very well, the issue is as good as closed.
Very satisfying to see this resolved after so many years.
