### ISSUE TITLE
Amy's Warrior Feather doesn't appear (Disable Node Limit)

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/sadx-mod-loader#132]
When the Mod Loader is enabled, Amy's Warrior Feather upgrade doesn't appear on her head. It's always missing, including the cutscene where she gets it, on a complete save file and when the "Have all upgrades" code is enabled. The upgrade shows up on the same save file when the Mod Loader is disabled.

**Comment by PiKeyAr** [comment]
Disabling the "Increase node limit patch" seems to resolve this,

**Comment by Sora-yx** [comment]
Fixed in 9ac8ff019862106cdc8ae7cd34c1d60342d65144
