### ISSUE TITLE
saves from steam don't load/aren't anywhere

### ISSUE THREAD

**Issue by mosswoss** [X-Hax/sadx-mod-loader#135]
i've just downloaded this mod manager to make big's stages easier, but my save from steam doesn't show up. help.

**Comment by PiKeyAr** [comment]
Do you have "Extended save support" enabled in the Game Config/Patches tab?

**Comment by mosswoss** [comment]
> Do you have "Extended save support" enabled in the Game Config/Patches tab?

i actually didn't this is so embarassing

**Comment by mosswoss** [comment]
also side note how do i stop the camera from going into first person the second i don't move?

**Comment by mosswoss** [comment]
nvm i got it as well how do i delete a thread
