### ISSUE TITLE
Gamecube Mayflash adapter not working with SA mods

### ISSUE THREAD

**Issue by pt23X** [X-Hax/sadx-mod-loader#138]
It is possible to play the original game using the gamecube controller with the mayflash adapter, and configure the buttons using steam big picture mode. However after installing the sa mods the controller is completely unresponsive.

I have tried enabling and disabling mods to test it out, I also have tried both input options, however it wast no avail. 

It was not the case with another third party ps controller I have, since the game responded to the inputs and I could map it without issue.

**Comment by pt23X** [comment]
Never mind It's just controller number 1 is recognized as 3

**Comment by PiKeyAr** [comment]
It's possible, but you may need to do something with the adapter to make it recognize the controller as the first one, otherwise it will be mapped to Player 3 in the game. At the moment we don't have a way to assign player IDs manually.

**Comment by pt23X** [comment]
You're exactly right it works if i use the second slot of the adapter, thank you and thanks for all the great work!
