### ISSUE TITLE
Changing the screen crashes the game

### ISSUE THREAD

**Issue by Angalo-plus-plus** [X-Hax/sadx-mod-loader#139]
I did the Game Health Check, which gave me a list of things it "fixed", which did nothing.
• re-jp.mpg is modified.
• re-us.mpg is modified.
• sa1.mpg is modified.
• sa2.mpg is modified.
• sa3.mpg is modified.
• sa4.mpg is modified.
• sa5.mpg is modified.
• sa6.mpg is modified.
• sa7.mpg is modified.
• sa8.mpg is modified.
• sonic.exe is modified.

I reinstalled the mod manager which didn't do anything. I had to reinstall the game and the manager. I dunno what is happening.

[YouTube](https://youtu.be/JGUG0WN3Qs4). I tried to make it as quick and short as possible. Sorry if it's too long.

I love what you guys do. Love this game and you guys. <3

**Comment by PiKeyAr** [comment]
Can you retest with the latest version pls? There were some fixes related to multiple screens and borderless fullscreen, it should work better now.
