### ISSUE TITLE
Tails Ice Cap Crash

### ISSUE THREAD

**Issue by skmistress** [X-Hax/sadx-mod-loader#140]
**Description**
The game crashes when I try to load Ice Cap in Tails' story. I have no clue what's causing this. 

**Steps Taken**
1. Go to Ice Cap as Tails
2. See error

**Expected behavior**
Load Tails' version of Ice Cap as expected.

[CrashDump_30_03_2024_22_48_02.dmp](https://github.com/X-Hax/sadx-mod-loader/files/14813957/CrashDump_30_03_2024_22_48_02.dmp)
[ModList_03_30_2024_22_48_04.json](https://github.com/X-Hax/sadx-mod-loader/files/14813958/ModList_03_30_2024_22_48_04.json)

**Comment by PiKeyAr** [comment]
Are you sure this is a Mod Loader bug?

**Comment by skmistress** [comment]
...No, not really. Now that I read your comment, I'm scared. Please don't hurt me, I wear glasses and I can't afford to replace them.

**Comment by cheatfreak47** [comment]
> ...No, not really. Now that I read your comment, I'm scared. Please don't hurt me, I wear glasses and I can't afford to replace them.
 
Har har. What he's asking is, are you sure it's not some mod you have loaded rather than the mod loader itself? Checking into your json file, you have a LOT of stuff loaded, have you tried running the level without all those mods or tried using trial and error to verify that it's not some mod you have causing the crash?

**Comment by skmistress** [comment]
> > ...No, not really. Now that I read your comment, I'm scared. Please don't hurt me, I wear glasses and I can't afford to replace them.
> 
> Har har. What he's asking is, are you sure it's not some mod you have loaded rather than the mod loader itself? Checking into your json file, you have a LOT of stuff loaded, have you tried running the level without all those mods or tried using trial and error to verify that it's not some mod you have causing the crash?

If I'm being completely honest, I reported this because I was really convinced it wasn't a problem with any of the mods. I'll actually bite the bullet and try trial and error now, sorry for wasting you guys' time.

**Comment by skmistress** [comment]
Turns out it was just because of Better Tails AI being under Multiplayer, whoops! Feel free to murder me in cold blood for such an easily solvable problem that didn't need to be reported at all!
