### ISSUE TITLE
Weird performance issues in the Save Select screen

### ISSUE THREAD

**Issue by ViperAcidZX** [X-Hax/sadx-mod-loader#142]
Bringing my previously reported issue to the proper repository, but I also followed suggestions to update the mod loader and made sure to uncheck Resizable Window (which I also had disabled already when I made the initial report), and the Save Select screen is still causing the framerate to run at sub-30 FPS when this didn't happen before the major updates to the mod manager and loader. I also did a clean re-install of my game and it is installed in an SSD, the issue still persists.

**To Reproduce**
1. Perform a clean install of SADX on Steam.
2. Patch and downgrade the game to the 2004 version with SADX Mod Installer from PkR's website.
3. Launch the game after SADX Mod Installer has finished converting the game and installing mods.
4. Go to the Save Select screen after the Title Screen, frame-rate suddenly runs worse until the Main Menu appears.

**Expected behavior**
The game should be able to run at full 60 FPS in all areas despite how out-of-date my PC is since I never had this issue before, regardless of resolution or tweaks.

**Desktop (please complete the following information):**
Windows 10 Home (64-bit)
8 GB DDR3 RAM (@ 1600 MHz)
Nvidia GeForce GTX 1060 6 GB
AMD FX-4350 @ 4.2 GHz (4 cores)

**Additional context**
Latest d3d8to9 was also installed via SADX Mod Installer, and made sure to disable Resizable Window and installed the latest updates.

**Comment by PiKeyAr** [comment]
Does this still happen when you do the following?
1) Disable the Crash Guard patch in Game Config/Patches;
2) Disable all mods and the patches but keep the Mod Loader enabled;
3) Disable the Mod Loader.

**Comment by Jesus-PK** [comment]
I gave it a try on my own machine and can confirm that Crash Guard was causing a slight FPS drop in the Save Select screen (in my case it was just dropping to 50 ~ 54, but without it enabled it stayed at the usual constant 59 ~ 60

**Comment by ViperAcidZX** [comment]
I can also confirm that the Crash Guard patch was causing the problem and disabling it fixed the issue. I also checked if any of the mods I used (though they were only the ones that were pre-included with Mod Installer) didn't introduced any of the save screen performance problems, and disabling the mod loader (which had to be done manually since I couldn't find the option to do that in the Mod Manager's UI) only brought back the 2004 PC port's problems kicking and screaming but it is not related to the Crash Guard patch.

**Comment by PiKeyAr** [comment]
Try again with the latest version?

**Comment by ViperAcidZX** [comment]
New updates to the loader seemed to have fixed the framerate issues on the Save Select screen with Crash Guard enabled. Thank you!

**Comment by PiKeyAr** [comment]
Thanks for testing!

Further discussion in #143
