### ISSUE TITLE
FunctionHook slower than Trampoline

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/sadx-mod-loader#143]
**Description**
FunctionHook causes a significant performance impact in comparison to Trampoline. This can be seen when a FunctionHook is placed on njSetTexture (Direct3D_SetTexlist in old disasm).

**Steps Taken**
1. Enable the Crash Guard patch in the Mod Manager/Game Config/Patches.
2. In CrashGuard.cpp, uncomment lines 219 and 240, and comment out lines 220 and 239 (see [this commit](https://github.com/X-Hax/sadx-mod-loader/commit/3b4071a0d8134efe25d1337803548cad47dadadd))
3. Build and replace the Mod Loader DLL file.
4. Run the game and go to the File Select screen. Framerate may drop significantly depending on the CPU.

**Expected behavior**
The File Select screen should run at 60 FPS.

**Comment by MainMemory** [comment]
![image](https://github.com/X-Hax/sadx-mod-loader/assets/6082665/afc03ff1-b0c3-44ff-bdc8-abc78a4c6b00)
Turns out this is the culprit.
