### ISSUE TITLE
cgi cutscenes automatically skipped

### ISSUE THREAD

**Issue by KeltheHedgehog** [X-Hax/sadx-mod-loader#148]
Dunno what I did but
![Screenshot (659)](https://github.com/X-Hax/sadx-mod-loader/assets/79247091/40e532f5-5378-4c58-b176-af0c98b0c909)
![Screenshot (660)](https://github.com/X-Hax/sadx-mod-loader/assets/79247091/9fe8948b-dac6-416d-b340-b259db7449ea)
![Screenshot (661)](https://github.com/X-Hax/sadx-mod-loader/assets/79247091/0ca6475f-b0c3-44f5-b7a8-3516641d12ce)
![Screenshot (662)](https://github.com/X-Hax/sadx-mod-loader/assets/79247091/b8de7e72-e2d8-4ffe-8684-cefce6ce3d59)
![Screenshot (663)](https://github.com/X-Hax/sadx-mod-loader/assets/79247091/d3d9be27-a6af-4964-898b-706e80380f66)
 the cgi cutscenes suddenly skipped

**Comment by PiKeyAr** [comment]
See here: https://github.com/X-Hax/SADXModdingGuide/wiki/SADX-Troubleshooting-Guide#the-game-skips-videos

Closing since this isn't an issue with the Mod Loader.

**Comment by KeltheHedgehog** [comment]
So I did all the step in the troubleshooter but they're still skipping to the in game cutscene
