### ISSUE TITLE
API function "find_by_dll" from the ModList struct doesn't work as intended and throws a false positive on non-dll mods.

### ISSUE THREAD

**Issue by Jesus-PK** [X-Hax/sadx-mod-loader#151]
**Description**
Using `find_by_dll` from the ModList struct produces unwanted results. Usages like:
`auto MOD_CharacterSelect = helperFunctions.Mods->find_by_dll(GetModuleHandle(L"SADXCharSel"));`
or
`bool MOD_CharacterSelect = false;`
`MOD_CharacterSelect = helperFunctions.Mods->find_by_dll(HMODULE("SADXCharSel")) != nullptr;`
or
`bool MOD_CharacterSelect = false;`
`MOD_CharacterSelect = HelperFunctionsGlobal.Mods->find_by_dll(GetModuleHandle(L"SADXCharSel")) != nullptr;`

The checks work fine and detect when the mod is loaded under the conditions given (for example, if loaded below the target mod or loaded at all). But the check throws a false positive when you load a mod that doesn't include a .dll file.

**Steps Taken**
1. Make a `find_by_dll` check in your code and a condition to trigger if true.
2. Load your mod alongside any other mod that doesn't use a .dll file.
3. Your condition with throw a false positive.

**Expected behavior**
Condition shouldn't throw a false positive when it finds a mod that doesn't have a .dll file, like with the old `GetModuleHandle` method.

**Comment by MainMemory** [comment]
If you're saying that not having the mod loaded causes a false positive, there's really no way around that, because in that case `GetModuleHandle` will return `NULL`, and, well, any mod with no DLL will have a DLL handle set to `NULL`. Your code needs to check that the handle is not `NULL` before calling `find_by_dll`

**Comment by MainMemory** [comment]
I mean, I guess we could special-case `NULL` to always return `nullptr`, and make it impossible to find a mod with no DLL through `find_by_dll`.

**Comment by Jesus-PK** [comment]
> If you're saying that not having the mod loaded causes a false positive, there's really no way around that, because in that case `GetModuleHandle` will return `NULL`, and, well, any mod with no DLL will have a DLL handle set to `NULL`. Your code needs to check that the handle is not `NULL` before calling `find_by_dll`.

Not having the target mod loaded would work fine, but loading a unrelated mod that doesn't use a .dll would trigger the false positive. I couldn't replicate the issue when using the old `GetModuleHandle` method, but I'll try to give a try to what you said.
