### ISSUE TITLE
Game crashes after the Sonic Team logo regardless of reinstalling, deactivating mods, SADX has crashed at 2938a210 (dsfOggDemux2.dll).

### ISSUE THREAD

**Issue by lordpsi99** [X-Hax/sadx-mod-loader#154]
[00_00_44_Dump_Sonic_HH.dmp](https://github.com/user-attachments/files/16827215/00_00_44_Dump_Sonic_HH.dmp)
[00_00_44_extra_info_Sonic_HH.txt](https://github.com/user-attachments/files/16827216/00_00_44_extra_info_Sonic_HH.txt)
[00_00_44_ModList_Sonic_HH.json](https://github.com/user-attachments/files/16827217/00_00_44_ModList_Sonic_HH.json)

**Description**
The game crashes after the Sega logo if animated Sonic Team logo is on, otherwise it crashes after the static Sonic Team logo. I tried with no mods active, reinstalling after revo uninstalling (program that uninstalls more thoroughly) multiple times. I did try installing the rtx mod but it said my radeon rx 5700xt was incompatible when I launched it, so i uninstalled that mod. I tried shift+del the game folder, too. Absolutely no results on google when I looked up   SADX has crashed at 2938a210 (dsfOggDemux2.dll). It seems that Sonic Adventure DX should not even be using that dsfOggDemux2.dll, according to web searches and searching my whole computer for it. I only have the dll in mpcstar and xiph.org folders but they are different sizes.

**Steps Taken**
A vanilla Steam SADX works perfectly, to recreate the problem, I only have to use the SA Mod Installer and SA Mod Loader, or double clicking either the sonic.exe or sonic_original.exe after the mod installer finishes.

trying to start with no mods active gives me the same result, only lower resolution Sega and Sonic Team logo.
[22_24_32_Dump_Sonic_HH.dmp](https://github.com/user-attachments/files/16827328/22_24_32_Dump_Sonic_HH.dmp)
[22_24_32_extra_info_Sonic_HH.txt](https://github.com/user-attachments/files/16827329/22_24_32_extra_info_Sonic_HH.txt)
[22_24_32_ModList_Sonic_HH.json](https://github.com/user-attachments/files/16827330/22_24_32_ModList_Sonic_HH.json)

**Expected behavior**
Well, I'm expecting the game to work like it does on my Steam Deck and on my other Windows 10 computer at my parents house with the same specs, except a couple months older and just put in an Asus RTX 3050 6gb (really should be called the rtx 3030 because it's completely different to the 8gb, and doesn't need auxiliary power).

If you have a Crash Dump, please include the file on this issue along with the copied json file.

**Comment by PiKeyAr** [comment]
You have ffdshow and some other codecs installed, which are known to interfere with the game's video player.
![image](https://github.com/user-attachments/assets/f8a23668-365b-4a21-8601-5518a941dc7f)
You also have Nahimic OSD related DLLs, which may or may not cause problems with the Mod Manager or the game.
![image](https://github.com/user-attachments/assets/7525d256-d166-4a3e-a059-f0da8d9b779b)

**Comment by lordpsi99** [comment]
I seem to have fixed it by updating xiph. Came here to update things but you already replied. Oh, it crashed again, but this time after selecting Adventure. I was so close.
[01_07_22_Dump_Tails_HH.dmp](https://github.com/user-attachments/files/16827404/01_07_22_Dump_Tails_HH.dmp)
[01_07_22_extra_info_Tails_HH.txt](https://github.com/user-attachments/files/16827405/01_07_22_extra_info_Tails_HH.txt)
[01_07_22_ModList_Tails_HH.json](https://github.com/user-attachments/files/16827406/01_07_22_ModList_Tails_HH.json)

also, I hate Sonic Studio 3, the motherboard audio software from asus. I preferred Realtek, like my previous Asus mb had.
I'll try uninstalling mpcstar and xiph.
How do I fix the OSD issue?

**Comment by lordpsi99** [comment]
uninstalling mpcstar and xiph did not change anything

**Comment by PiKeyAr** [comment]
The crash in the Tails dump is in the vertex welding function, which indicates a problem with some character mod. This repo is not meant for troubleshooting mods, it's for bugs in the Mod Loader.

If you uninstalled the codecs and still get the crash in the same DLL, it means the DLLs are still loaded so they weren't uninstalled correctly.

**Comment by lordpsi99** [comment]
Deactivating all the mods related to the DX models got me further. I think we fixed it. Thanks so much for your help, time and extreme patience with me.

**Comment by lordpsi99** [comment]
Thank you so much, for not only fixing my computer but fixing the whole game! It feels like a finished game, and I haven't felt this way since 1999 or so, when renting the NA version and a Dreamcast system here for the first time. It looks and feels like an HD remaster, as good as Metroid Prime Remastered.
