### ISSUE TITLE
my mod loader wont install

### ISSUE THREAD

**Issue by TTRNoah** [X-Hax/sadx-mod-loader#155]
my mod loader wont install even if i uninstall it and reinstall it back
![why](https://github.com/user-attachments/assets/1571ddb6-4357-4a8d-89c8-694e4461d73e)

**Comment by PiKeyAr** [comment]
Not a Mod Loader issue

**Comment by TTRNoah** [comment]
> Not a Mod Loader issue

so its a mod manager issue
