### ISSUE TITLE
CD check Prevents game from booting.

### ISSUE THREAD

**Issue by DaemionJ** [X-Hax/sadx-mod-loader#158]
**Description**
CD check prevents me from opening the game. 
**Steps Taken**
1. Open launcher.
3. Click on 'Save & Play'
5. See error
**Expected behavior**
Game would Boot up without issue

**Comment by PiKeyAr** [comment]
There's a "Disable CD Check" patch in the Mod Manager. If the game doesn't work with this patch enabled, you have the wrong version of the game.

**Comment by DaemionJ** [comment]
> There's a "Disable CD Check" patch in the Mod Manager. If the game doesn't work with this patch enabled, you have the wrong version of the game.

when I click the patch list, it comes up empty. It also isnt in the cheats tab.
