### ISSUE TITLE
One-click install support for GitHub and self-hosted mods

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/sadx-mod-loader#39]
The one-click install functionality is a great concept, and it could be expanded further for GitHub and self-hosted mods. That would allow to have clickable lists of mods (hosted anywhere) on a web page, which could function as a substitute for a mod database.

The name of the author/mod could be embedded into the URL itself.

**Comment by cheatfreak47** [comment]
I suggested this in IRC a while back too, this is definitely a good idea

**Comment by PiKeyAr** [comment]
Added in [this commit](https://github.com/X-Hax/sadx-mod-loader/commit/3a642ac1af40d8d3f922f8955de900c50e220c44).
