### ISSUE TITLE
(request) Update Retry feature

### ISSUE THREAD

**Issue by KirbyJoe** [X-Hax/sadx-mod-loader#41]
Sometime when I use the Mod Loader, I encounter an update error and I need to retry this update, but something is missing. It’s the retry feature. Many software can retry the update when the error has encountered, but why SADX Mod Loader has missing this? I strongly recommend to add this feature as a part of more user-friendly experience.

**Comment by PiKeyAr** [comment]
Is this still relevant? I disconnected while it was downloading an update, and it just sat there until I reconnected, then it resumed downloading the update from the same position.

**Comment by PiKeyAr** [comment]
Moved to https://github.com/X-Hax/SA-Mod-Manager/issues/43
