### ISSUE TITLE
Cheat code to disable “Auto-hints”

### ISSUE THREAD

**Issue by KirbyJoe** [X-Hax/sadx-mod-loader#47]
In Sonic Adventure DX, when the player restarts the level, the hint will automatically shows up. Also, there are 2 bosses have the “auto-hints” during the battle, Egg Viper and Chaos 6 (Big). The first one is when you defeat it and Eggman is about to do his final attack, and the second one is when the battle starts. It’s too annoying and intrusive for some players. When I played it, I thought it’s too unnecessary for me. I know the sequel called Sonic Adventure 2’s Omochao hints are annoying, but SA1/DX’s “auto-hints” are annoying too!

**Comment by KirbyJoe** [comment]
I changed the title for bit because I’m actually talking about the gameplay cheat code, not the Mod Loader option.

**Comment by kellsnc** [comment]
The code was added to the Mod Loader with df4637f, closing this now ^^
