### ISSUE TITLE
TestSpawn: Cutscene preview

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/sadx-mod-loader#87]
A good addition to the Mod Loader's Test Spawn functionality would be an option to start the game on a specific cutscene. I have a working implementation in [this fork](https://github.com/PiKeyAr/sadx-test-spawn/blob/master/sadx-test-spawn/mod.cpp) of the original TestSpawn mod, though it might be a bit too hacky for the Mod Loader.

The basic idea is to patch event IDs used for demos that play after waiting on the title screen. The main problem with this approach is the need to set the necessary story progression flags manually for each cutscene, and some cutscenes require workarounds such as removing objects that load music or bosses, or trigger the end of the stage. Most of this is already handled in the fork so it could be repurposed if the same approach is implemented in the Mod Loader.

A better implementation would require understanding how the game's story sequences work, and how to manipulate them similar to SADX Preview's "Easy Menu", although even "Easy Menu" fails to load some cutscenes.

**Comment by kellsnc** [comment]
So I made [a simpler version](https://github.com/X-Hax/sadx-mod-loader/tree/testspawn-events) of your fork. It works by replacing the copyright GameMode, setting up the needed variables, and sending the game to the Adventure/Level GameMode where it will handle the event.

I have not yet ported the [patches](https://github.com/PiKeyAr/sadx-test-spawn/blob/master/sadx-test-spawn/mod.cpp#L136) you made but I plan to once I'm back from holidays (unless you port them beforehand).

Will be away for a week, but feel free to suggest/edit things ^^

**Comment by PiKeyAr** [comment]
List of issues with the current implementation:


- [ ] All cutscenes: Sync issues with the "Pause when inactive" option. Same as with the regular demo cutscenes and gameplay demos.

**Cutscenes not loading or unloading too early**
- [ ] EV0024 Egg Viper: The boss fight interferes with the cutscene
- [ ] EV0031 Tails rescued by Sonic: Cutscene finishes too early
- [ ] EV0048 Tails meets Sonic on Red Mountain: Cutscene finishes too early
- [ ] EV00DA Big saves Froggy in Hot Shelter: Conflicts with the scene "Big spots Froggy inside the tanks"

**Sound issues**
- [ ] EV0030 Tails Intro: Background noise of the airplane doesn't play
- [ ] EV0051 Tails beats the Egg Viper: Background crowd noise doesn't play
- [ ] EV0070 Amy and Birdie head back to the Egg Carrier: Door shutter sound doesn't play

**Character/camera position issues**
- [ ] EV0083 Knuckles enters the Past: Possibly wrong position/angle
- [ ] EV00C3 Gamma's objectives changed: Gamma not seen in the beginning
- [ ] EV00F9 Sonic wakes up from a snooze cruise: Wrong camera angles and/or character positions
- [ ] EV0103 This must be the way to the Sky Deck (Sonic): Wrong camera/character position
- [ ] EV0107 Emergency alert cancelled (Sonic): Wrong camera/character position
- [ ] EV0113 This must be the way to the Sky Deck (Tails): Wrong camera/character position
- [ ] EV0122 Knuckles sensing the Master Emerald: Wrong camera/character position
- [ ] EV0131 Amy beats Hedgehog Hammer: Wrong camera/character position
- [ ] EV0140 Gamma is told to get the Jet Booster: Wrong camera/character position
- [ ] EV0150 Emergency alert cancelled (Big): Wrong camera/character position
- [ ] EV0165 Sonic gets the Crystal Ring: Odd camera angles
- [ ] EV016E Gamma gets the Laser Blaster: Wrong character/camera position

**Lighting issues**
- [ ] EV0141 Gamma heading to Hot Shelter: Wrong lighting
- [ ] EV0142 Gamma sees E101R: Wrong lighting

**Other issues**
- [ ] EV0166 Sonic gets the Light Speed Shoes: Minor animation glitch at start
- [ ] EV017A Passage to Angel Island opens (Sonic): The rocks breaking off animation doesn't play
- [ ] EV017B Passage to Angel Island opens (Tails): The rocks breaking off animation doesn't play
- [ ] EV017CPassage to Angel Island opens (Gamma): The rocks breaking off animation doesn't play

**Comment by kellsnc** [comment]
I have worked all day on improving the testspawn event branch, all of the issues you originaly posted are fixed!

Note that I removed the position thing until we find a better solution, maybe the events could manually be patched ^^

Issues:
- [ ] EV0122: Pool shouldn't be full
- [ ] EV0017, EV0048: SET Objects
- [ ] EV0088: SET Objects
- [ ] EV0103 This must be the way to the Sky Deck (Sonic): wrong position
- [ ] EV0113 This must be the way to the Sky Deck (Tails): wrong position
- [ ] EV0131 Amy beats Hedgehog Hammer: wrong position
- [ ] EV0140 Gamma is told to get the Jet Booster: wrong position

**Comment by PiKeyAr** [comment]
Very good. I updated some cutscenes where Gamma is suppposed to have the Jet Booster. Also tested a bit more and found some regressions and a couple of new issues. You are probably aware of some of these but I decided to list them all to keep track of our progress.

**Cutscenes not working**
- [ ] EV0024: Black screen
- [ ] EV00B5: Cutscene interrupted by boss fight
- [ ] EV016C: Cutscene not playing
- [ ] EV016E: Cutscene not playing
- [ ] EV0170: Big's bed is in the wrong position, weird animation glitches later in the cutscene. Seems to conflict with Big's intro?
- [ ] EV0177: Ice Stone doesn't appear

**Wrong time of day**
- [ ] EV0014: Should be night
- [ ] EV0015: Should be day
- [ ] EV0042: Should be evening
- [ ] EV00D3: Should be night
- [ ] EV016A: Not sure if this should be specifically night, normally Fighting Gloves can be obtained during the day

**Wrong character position**
- [ ] EV0122: Knuckles should be at the bottom of the pool

**Wrong lighting**
Wrong lighting with Lantern Engine is back after the last update. This happens because Lantern Engine checks story flags for Egg Carrier sinking before these flags are set in test spawn.
- [ ] EV0141
- [ ] EV0142

**Other glitches**
- [ ] EV0017: Sonic attempts to jump onto the Tornado. In the vanilla game he is frozen in place (I think because of the victory pose not clearing properly or something). I don't know if this should be fixed in the actual cutscene or not, but those SET objects get in the way of his jump either way, so there's no good "vanilla" solution for this problem.
- [ ] EV0048: Same as above
- [ ] EV00BA: Gamma's animation is frozen until he walks towards the Chao (doesn't happen during a normal playthrough)
- [ ] EV00C3: Same issue as in the last report

**Music issues**
- [ ] EV0020: Plays stage music
- [ ] EV008D: Plays stage music

**General issues**
- [ ] The time of day hack in the GUI/command line now crashes the game
- [ ] Character position no longer works in Adventure Fields

**Comment by PiKeyAr** [comment]
About EV0088: I don't think this is a real problem. Many cutscenes, including the one before this boss fight, load SET objects normally and you can see rings around. If you somehow managed to beat Chaos 2 without collecting any rings it would probably look the same. The other SET objects in this cutscene (chandelier, tables) are part of level decorations that are also retained during a normal playthrough.

**Comment by kellsnc** [comment]
Thanks, will fix soon enough! About the position and time of day regressions it's things I removed but will put back, I have an idea on how to handle positions better ^^

About lantern engine checking too soon, i guess the flag function should run on init, hopefully that won't break anything!

**Comment by PiKeyAr** [comment]
I'm not sure how to fix EV0024. For some reason it's really hard to get working as a cutscene, but it will play fine if you just set the level to Egg Viper without event stuff. Rather than dropping you straight into the boss fight, it starts with the cutscene. If nothing else works, we could just do that. The level object checks if the cutscene has already played, so in the non-event TestSpawn you just need to set CutsceneFlags[36] to 1 to skip the cutscene.

**Comment by PiKeyAr** [comment]
Potential enhancement to consider: Override levels and characters in cutscenes with the "Level" and "Character" options in the GUI if they are enabled. This would allow people to play around with the cutscenes a bit more.

**Comment by kellsnc** [comment]
EV0024 used to work before, I will check later ^^ and why not for overriding character? unless it can cause crashes.

You're missing a `break` line 419 I think btw!

**Comment by PiKeyAr** [comment]
- [ ] Worth checking: in EV001D Sonic's jump from the ship is staggered by something (possibly the invisible wall used for the boundaries in the boss fight). In a regular playthough he jumps out normally.

**Comment by PiKeyAr** [comment]
- [ ] EV0022: Chao missing

**Comment by kellsnc** [comment]
Fixed everything but EV0020, EV0024 and EV001D. The latter is weird, the function that sets up the arena collision doesn't get called; though I noticed a collision in the landtable itself. Anyway, couldn't get it to work. Will check it again, and the other two, later ^^

**Comment by PiKeyAr** [comment]
Tested with the latest commit. Very good, looks close to a complete state and way beyond what my original fork did.

I've only been able to test Sonic's and Tails' stories so far, but I've played around a bit more thoroughly this time

**Cutscenes not working**
- [ ] EV0024: Cutscene not playing
- [ ] EV0031: Cutscene ends too early
- [ ] EV0048: Cutscene ends too early

EV001D may be fixable with a hack that loads Chaos 6 and immediately sets its state to defeated, or something that disables the player's collision with walls.

**Story progression issues**
I don't think the stuff below is critical for this update, but since you mentioned that you want to be able to continue playing after the cutscene finishes, I've also tried to mess around with that. Here's a list of issues I've run into trying to do it, most of this is story flags but there were a few crashes.
EV0002: Goes to Chaos 0 instead of Station Square
EV0009: Goes to Station Square night
EV0012: Crashes after "Now you can play with Amy"
EV0016: Angel Island passage not open
EV0017: Goes to Red Mountain 2 instead of Sky Chase
EV001D: Goes back to an empty Chaos 6 level
EV0020: Goes back to the mural room
EV0021: Crashes as you try to approach the altar
EV0026: Goes back to Mystic Ruins
EV0040: Jungle entrance not open
EV0051: Hangs with frozen controls in the Mystic Ruins
EV0052: Same as above


I've also had sound effects stop working and the game crashing after EV0022 and EV0023, but I couldn't reproduce it. I've had similars issue before on a different computer and in an unrelated situation so it's probably not an issue with testspawn.

**Comment by PiKeyAr** [comment]
Position works fine.
- [ ] Setting the time of day in the Mystic Ruins makes the game crash
- [ ] Setting position doesn't work in the Chao Gardens (probably not worth it though)
- [ ] Character and level override for cutscenes

**Comment by kellsnc** [comment]
Thank you, will fix soon enough! I'm pretty sure that I fixed 024 yesterday, maybe I did a last minute change that broke it again... it's related to timing and I did change that a bit ^^

As for story continuation I can try to look at it, but yeah maybe we could do that in a new batch specifically centred around that :)

Btw I just saw that you added rotation in your fork as a forth -p argument, should I restore that? Maybe rotation is not that useful?

**Comment by kellsnc** [comment]
I fixed everything you have reported so far.

As for the level and character override it's crashing the game in many ways and causing all sorts of issues, I do not think it's worth it.

**Comment by PiKeyAr** [comment]
Thanks, will be testing later today.

>As for the level and character override it's crashing the game in many ways and causing all sorts of issues, I do not think it's worth it.


That is fine as long as the override is still a possibility. Most cutscenes would crash, but some cutscenes can be played with other characters or in other levels. We don't have to make sure all cutscenes work with all characters in every level, that's unrealistic. Just making the switches work is good enough.

**Comment by PiKeyAr** [comment]
I've tried all cutscenes except Sonic's and Tails' stories which I played earlier. It's almost good to go, just a few issues left, most of which are minor. I've fixed a couple of issues I noticed, here are the other things:

- [ ] EV006F: Level music plays
- [ ] EV0071: Crashes on cutscene finish (ProcessNBFile)
- [ ] EV0080: Two Chaoses, weird timing issues - event running twice?
- [ ] EV0083: Knuckles lands instead of just standing still at the start of the cutscene
- [ ] EV00C7: Crashes on cutscene finish (ProcessNBFile)
- [ ] EV0122: There's a water splash effect and sound even though the pool isn't filled with water
- [ ] EV0167: Sonic not using the standing animation near the end of the cutscene

I've also been getting inconsistent crashes with the faulty module being `ntdll.dll`. It happens if you try to do something ingame after a cutscene finishes, and it may be related to sound since I noticed sometimes sound effects don't play. I can't tell if this is an issue with testspawn or the game (I've had a similar missing sound/random crash issue before on a different PC without testspawn) but if it happens consistently on other PCs it could indicate something going wrong with the cutscene thread? I don't really know...

Since this update only aims to allow cutscenes to play, I think this can be investigated later. The crashes in EV0071 and EV00C7 aren't related to this though and it would be nice if they could be fixed.

**Comment by kellsnc** [comment]
So there is an HeapAlloc issue which caused ProcessNBFile and sounds to crash, maybe some initialization thing is skipped over? or maybe it doesn't like the loader? But yeah it should be fixed before we publish this.

**Comment by PiKeyAr** [comment]
Crashes fixed by replacing the level ID with Egg Carrier.

About 006F and 0122: I think this stuff is happening because the objects load before the event is set. At least the Final Egg level object checks if EV_MainPtr is null, and if it is null it calls the function that starts playing the music and stuff.

**Comment by PiKeyAr** [comment]
After the last update in EV0083 Knuckles doesn't play the landing animation anymore, but it looks like the location is wrong again and Tikal music doesn't play

**Comment by kellsnc** [comment]
> After the last update in EV0083 Knuckles doesn't play the landing animation anymore, but it looks like the location is wrong again and Tikal music doesn't play

Likely side effect of launching event a frame sooner to fix EV006F, we'll probably have to revert the change and fix 06F with nops.

**Comment by PiKeyAr** [comment]
I've added a few hacks and also restored the level and character override for events. I'll add a small warning in the UI saying it can cause the game to become unstable.
All in all this isn't super clean looking but it works... Apart from a small animation glitch at the end of EV0167 I think this is good enough. I still think it ended up too hacky for the Mod Loader but if we're going to include it at all, this is probably as good as it can get.

**Comment by kellsnc** [comment]
The cleanest solution would be to remove the story progression stuff which is what makes it a mess (we basically have two different ways of launching events.) But it allows for basic story continuation which can be a useful feature!

I think it works well, but let see what the others think ^^
